theme = "tokyonight"

[editor]
line-number = "relative"
cursorline = true
popup-border = "all"
auto-save = true
auto-format = true
completion-timeout = 5
completion-replace = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "version-control",
]

[editor.lsp]
display-inlay-hints = true

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
