theme = "tokyonight"

[editor]
line-number = "relative"
cursorline = true
popup-border = "all"
auto-save = true
auto-format = true
completion-timeout = 5
completion-replace = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "version-control",
]

[editor.lsp]
display-inlay-hints = true

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.normal.space.m]
o = [":open ~/.config/matemode/materound", ":write!"]
m = ":sh matemode"

[keys.normal.space.h]
o = ":sh gh browse %{buffer_name}:%{cursor_line} --commit=%sh{git rev-parse HEAD}"
p = [":insert-output gh browse --no-browser %{buffer_name}:%{cursor_line} --commit=%sh{git rev-parse HEAD}", ":clipboard-yank-join", "delete_selection"]
b = ":sh git blame -L %{cursor_line},+1 %{buffer_name}"
