#!/bin/bash
#
# Utiliza fzf y crea una sesion de tmux (si no existe) en
# el directorio objetivo.
#
# Creditos a: ThePrimeagen

EXCLUDE='**/.git'
INCLUDE="projects drafts .config .dotfiles"

DIRS=$(fdfind . --base-directory ~/. --type d --exclude $EXCLUDE --hidden --absolute-path $INCLUDE)
if [ -z "$DIRS" ]; then
    exit 0
fi

TARGET=$(echo "$DIRS" | fzf)
if [ -z "$TARGET" ]; then
    exit 0
fi

BASENAME=$(basename "$TARGET" | tr . _)

# If there is no active session with folder name, create session
if ! tmux has-session -t $BASENAME 2> /dev/null; then
    tmux new-session -ds $BASENAME -c $TARGET
fi

if [[ ! -z "$TMUX" ]]; then
    tmux switch-client -t $BASENAME 2> /dev/null
else
    tmux attach-session -t $BASENAME 2> /dev/null
fi
