#!/bin/bash
#
# Utiliza fzf y crea una sesion de tmux (si no existe) en
# el directorio objetivo.
#
# Creditos a: ThePrimeagen

function join_by {
  local separator=${1}
  local first=${2}
  if shift 2; then
    printf %s "$first" "${@/#/$separator}"
  fi
}

BASE=(~/projects ~/drafts ~/.dotfiles)
OPTS="--type directory --full-path --hidden --ignore --exclude .git"

DIRS=$(fd $OPTS . $(join_by " " ${BASE[@]}))
TARGET=$(join_by $'\n' ${BASE[@]} "$DIRS" | fzf)
if [ -z "$TARGET" ]; then
    exit 0
fi

BASENAME=$(basename "$TARGET" | tr . _)

# If there is no active session with folder name, create session
if ! tmux has-session -t $BASENAME 2> /dev/null; then
    tmux new-session -ds $BASENAME -c $TARGET
fi

if [[ ! -z "$TMUX" ]]; then
    tmux switch-client -t $BASENAME 2> /dev/null
else
    tmux attach-session -t $BASENAME 2> /dev/null
fi
