#!/bin/bash
#
# Utiliza fzf y abre el editor predeterminado
# en el directorio objetivo.
#
# Creditos a: Luke Smith

EXCLUDE='**/.git'
INCLUDE_REC="projects .dotfiles .config"

REC=$(fdfind . --base-directory ~/. --type f --exclude $EXCLUDE --hidden --absolute-path $INCLUDE_REC)

ALL="$REC$BARE"

TARGET=$(echo "$ALL" | fzf)
if [ -z "$TARGET" ]; then
    exit 0
fi

$EDITOR $TARGET
