#!/bin/sh
#
# Reinicia la computaodra, estableciendo windows por defecto en grub (unica vez)

WINDOWS_TITLE=$(grep -i "^menuentry 'windows" /boot/grub/grub.cfg | head -n 1 | cut -d "'" -f 2)
sudo grub-reboot "$WINDOWS_TITLE"
sudo reboot
