#!/bin/bash
#
# Create or attach to tmux session on zoxide directory

export KITTY_PWD=$(zoxide query --list | fzf)
BASENAME=$(basename "$PWD")

open -a kitty.app -n --args \
  --title $BASENAME \
  --session $HOME/.config/kitty/default.session
