#!/bin/sh
#
# Create or attach to tmux session on zoxide directory

DIRECTORY=$(zoxide query --list | fzf)
BASENAME=$(basename "$DIRECTORY")

open -a kitty.app -n --args \
  --title "$BASENAME" \
  --directory "$DIRECTORY"
